### ISSUE TITLE
模块资源找不到

### ISSUE THREAD

**Issue by karanatarm** [alibaba/jarslink#16]
我按demo新建一模块，在调用模块时报
java.lang.IllegalArgumentException: resources length is 0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
	at com.alipay.jarslink.api.impl.ModuleLoaderImpl.findSpringConfigs(ModuleLoaderImpl.java:183)
	at com.alipay.jarslink.api.impl.ModuleLoaderImpl.loadModuleApplication(ModuleLoaderImpl.java:126)
我的模板配置文件在resources/META-INF/spring/*.xml 下

**Comment by kiral** [comment]
需要放一个bean.xml在resources/META-INF/spring下，并且能编译到类路径中。
